name: NewYearFirework
version: 1.2
main: io.github.sugarmgp.newyearfirework.NewYearFirework
api-version: 1.16
commands:
  newyearfirework:
    aliases:
      - "nyf"
    description: "主指令"
permissions:
  nyf.commands.use:
    description: "使用插件的权限"
    default: op